Bits\IsoProductfeed\Controller\BackendController:
  path: /contao/iso_productfeed
  controller: 'Bits\IsoProductfeed\Controller\BackendController::__invoke'
  type: annotation
bits.iso-productfeed.controller.backendcontroller:
  path: /contao/iso_productfeed
  controller: 'Bits\IsoProductfeed\Controller\BackendController::__invoke'
  type: annotat
