    Bits\Themply\Controller\BackendController:
        path: /contao/iso_productfeed
        controller: Bits\Iso_Productfeed\Controller\BackendController::__invoke
        type: annotation
    
    bits.themply.controller.backendcontroller:
        path: /contao/iso_productfeed
        controller: Bits\Iso_Productfeed\Controller\BackendController::__invoke
        type: annotation

