parameters: null

services:
    _defaults:
        autowire: true
        autoconfigure: true

    Bits\IsoProductfeed\Routing\DynamicRouteLoader:
        arguments:
            $resourceResolver: '@Bits\IsoProductfeed\Service\ResourceResolver'
            $defaultFileName: 'default.xml'
        tags: ['routing.loader']

    Bits\IsoProductfeed\Service\ResourceResolver:
        arguments:
            $baseDirectory: '%kernel.project_dir%/files'
            
    Bits\IsoProductfeed\Controller\FeedController:
        tags: ['controller.service_arguments']

    Bits\IsoProductfeed\Contao\DC_IsoProductfeed:
        arguments:
            $twig: '@twig'

    Bits\IsoProductfeed\EventListener\DataContainer\IsoProductfeedOnSaveListener:
        tags: ['contao.callback']

    Bits\IsoProductfeed\EventListener\DataContainer\IsoProductsOnSaveListener:
        tags: ['contao.callback']

    Symfony\Component\Form\FormFactoryInterface:
        alias: 'form.factory'

    Bits\IsoProductfeed\:
        resource: '../../../src'
        exclude:
            - '../../../src/ContaoManager.php'
            - '../../../src/DependencyInjection'
            - '../../../src/Resources'
