parameters: null

services:
    _defaults:
        autowire: true
        autoconfigure: true
            
    Bits\IsoProductfeed\Routing\DynamicRouteLoader:
        autoconfigure: false
        arguments:
            $resourceResolver: '@Bits\IsoProductfeed\Service\ResourceResolver'
            $defaultFileName: 'default.xml'
        tags:
            - { name: 'routing.loader' }
        
    Bits\IsoProductfeed\Controller\FeedController:
        autoconfigure: false
        tags: ['controller.service_arguments']

    Bits\IsoProductfeed\Contao\DC_IsoProductfeed:
        arguments:
            $twig: '@twig'

    Bits\IsoProductfeed\EventListener\DataContainer\IsoProductfeedOnSaveListener:
        tags: ['contao.callback']

    Bits\IsoProductfeed\EventListener\DataContainer\IsoProductsOnSaveListener:
        tags: ['contao.callback']

    Symfony\Component\Form\FormFactoryInterface:
        alias: 'form.factory'

    Bits\IsoProductfeed\:
        resource: '../../../src'
        exclude:
            - '../../../src/Controller'
            - '../../../src/ContaoManager.php'
            - '../../../src/DependencyInjection'
            - '../../../src/Resources'
            - '../../../src/Routing'
